@startuml
' Modelo de domínio do sistema: Entrega 1.
'
' Este arquivo é o ponto de partida. Substitua pelo modelo da sua equipe.
' O diagrama precisa corresponder ao código entregue.
'
' Para gerar a imagem: instale o plugin PlantUML no IntelliJ, ou use
'   plantuml docs/modelo.puml
' e versione a imagem gerada ao lado deste arquivo.

skinparam classAttributeIconSize 0
hide empty members

class Item {
 - codigo: String
 - titulo: String
 - autoria: String
 - categoria : String
 - ano : int

 + Item(codigo : String, titulo : String, autoria : String, categoria : String, ano : int)
 + getCodigo(): String
 + getTitulo(): String
 + getAutoria() : String
 + getCategoria() : String
 + getAno() : int
 + getExemplares() : List<Exemplar>
}

class Exemplar {
 - tombo: String
 - disponivel: boolean

 + Exemplar (tombo : String, item : StatusExemplar, codigoDoItem : String)
 + getTombo(): String
 + isDisponivel(): boolean
}

class Usuario {
 - usuariosPorMatricula : Map<String, UsuarioView>

 + cadastrarUsuario(matricula : String, nome : String) : void
 + buscarUsuario(matricula : String) : UsuarioView
 + listarUsuarios() : List<UsuarioView>
 + desativarUsuario(matricula : String) : void
 + reativarUsuario(matricula : String) : void
}

class Emprestimo {
  - dataEmprestimo: LocalDate
  - dataDevolucao: LocalDate
}

Item "1" *-- "0..*" Exemplar : possui >
Usuario "1" -- "0..*" Emprestimo : realiza >
Exemplar "1" -- "0..1" Emprestimo : é emprestado >

@enduml
